# Generated by Django 5.1.6 on 2025-08-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="has_logged_in_before",
            field=models.BooleanField(default=False),
        ),
    ]
