# Generated by Django 5.1.6 on 2025-06-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outlet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outlet",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="outlet",
            old_name="contact_no",
            new_name="postal_code",
        ),
        migrations.RemoveField(
            model_name="outlet",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="outlet",
            name="location",
        ),
        migrations.AddField(
            model_name="outlet",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="outlet",
            name="avatar",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="outlet",
            name="city",
            field=models.CharField(default="123 Main Street", max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="outlet",
            name="country",
            field=models.CharField(default="123 Main Street", max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="outlet",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="outlet",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="outlet",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="outlet",
            name="owner_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="outlet",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="outlet",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="outlet",
            name="street_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="outlet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="outlet",
            name="name",
            field=models.CharField(max_length=150),
        ),
    ]
