# Generated by Django 5.1.6 on 2025-06-28 07:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outlet", "0002_alter_outlet_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outlet",
            name="address",
            field=models.CharField(
                blank=True, default=django.utils.timezone.now, max_length=255
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="outlet.outlet",
                    ),
                ),
            ],
            options={
                "ordering": ["outlet", "number"],
                "unique_together": {("outlet", "number")},
            },
        ),
    ]
