# Generated by Django 5.1.6 on 2025-06-28 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outlet", "0003_alter_outlet_address_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="table",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
