# Generated by Django 5.1.6 on 2025-06-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
