# Generated by Django 5.1.6 on 2025-06-19 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_menuitem_is_available"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
